export const links = {
  home: 'https://www.firestation.io/en',
  explorer: 'https://explorer.hyperlane.xyz',
  discord: 'https://discord.gg/VK9ZUy3aTV',
  github: 'https://github.com/0xfirechain',
  docs: 'https://docs.firestation.io',
  warpDocs: '',
  gasDocs: '',
  chains: '',
  twitter: 'https://x.com/0xfirechain',
  blog: '',
  tos: '',
  privacyPolicy: '',
  bounty: '',
  imgPath: 'https://cdn.jsdelivr.net/npm/@avenbreaks/hyperlane-registry@18.0.0/dist',
  transferFees: '',
  stake: 'https://donaswap.io',
  support: 'https://faucet.firestation.io',
};
